blog/urls.py
from django.urls import path
from .views import (PostListView,
 PostDetailView,
 PostCreateView,
 PostUpdateView,
 PostDeleteView,
 UserPostListView,
 PostLike
 )
from . import views
urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
	path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post-like/<int:pk>', views.PostLike, name='post_like'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),  
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('about/', views.about, name='blog-about'),
]


blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length = 100)
	content = models.TextField()
	date_posted = models.DateTimeField(default = timezone.now)
	author = models.ForeignKey(User, on_delete = models.CASCADE)
	likes = models.ManyToManyField(User, related_name="post_like")

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk':self.pk})
	def number_of_likes(self):
		return self.likes.count()

#Comments
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    name = models.CharField(max_length = 25)
    content = models.CharField(max_length = 220)
    date_commented = models.DateTimeField( auto_now_add=True)
	
    class Meta:
        ordering = ['-date_commented']
    """
    def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)
    """

blog/forms.py
from django import forms
from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'content']

blog/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User 
from django.views.generic import (ListView,
 DetailView,
 CreateView,
 UpdateView,
 DeleteView
 )
from .models import Post
from .models import Comment
from .forms import CommentForm
# Create your views here.
#sql
def home(request):
	context = {
		'posts' : Post.objects.all()
	}
	return render(request, 'blog/home.html', context)
#user
class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html' 
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5
    def get_queryset(self): #get the object if it exist
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author = user).order_by('-date_posted')
    
#posts
class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        form = CommentForm()
        post = get_object_or_404(Post, pk=pk)

        liked = False
        if self.request.user.is_authenticated:
            liked = post.likes.filter(id=self.request.user.id).exists()

        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['nuber_of_likes'] = post.likes.count()
        context['post_is_liked'] = liked
        context['form'] = form
        return context
    def post(self, request, *args, **kwargs):

        form = CommentForm(request.POST) #creates
        self.object = self.get_object() #;

        context = super().get_context_data(**kwargs);        
        post = Post.objects.filter(id=self.kwargs['pk'])[0]
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form

        if form.is_valid():
            name = form.cleaned_data['name']
            content = form.cleaned_data['content']
            comment = Comment.objects.create(
                name = name, content = content
            )
            form = CommentForm()
            context['form'] = form
            return self.render_to_response(context=context)
        if 'like' in request.POST:
            post = self.get_object()
            user  = request.user
            if user.is_authenticated:
                if post.likes.filter(id = user.id).exists():
                    post.likes.remove(user)
                else:
                     post.likes.add(user)
            return self.render_to_response(context=context)
        return self.render_to_response(context=context)
        
        print(context)
        return self.render_to_response(context=context)
    

    

class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	fields=['title', 'content']
	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False # else = error

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True 
        return False

#LIKE
def PostLike(request, pk):
    post = get_object_or_404(Post, id=request.POSR.get('post_id'))
    if post.likes.filter(id=request.user.id).exits():
        post.likes.remove(request.user)
    else:
        post.likes.remove(request.user)
    return HttpResponseRedirect(reverse('post-detail', args=[str(pk)]))
# 

def about(request):
	return render(request, 'blog/about.html', {'title' : 'about'})

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container article-content ">
	<h1>About us</h1>
	
	<p>Hello, and welcome to my website. I am very proud of the security features we have in our website.
	Thank you for giving me this opportunity to talk about it. My blog is written in Django, which is part of Python. Python is a very secure language, and Django is one of the most secure web frameworks available. This makes my website very safe and reliable. I am very happy with the results I have achieved so far, and I plan to continue using Django and Python to create innovative and exciting new websites.</p>
</div>

{% endblock content%}

blog/templates/blog/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
  <head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css'%}">
 	<!-------->

	 {% if title %}
	   	<title>Django Blog - {{ title }}</title>
	 {% else %}
	   	<title>Django Blog</title>
	 {% endif%}
  </head>
<body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
		    <div class="container">
	      <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
	            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
    	     		<span class="navbar-toggler-icon"></span>
	            </button>
	            <!-- Navbar Left Side -->
     		    	<div class="collapse navbar-collapse" id="navbarToggle">
        			    <div class="navbar-nav mr-auto">
	              			<a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
        	      			<a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
        			    </div>
        			 <div class="navbar-nav">
                  {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'post-create'%}">New post</a>
                  
                  <a class="nav-item nav-link" href="{% url 'profile'%}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
                  {% else %}
        	  	  		<a class="nav-item nav-link" href="{% url 'login'%}">Login</a>
          	  	    	<a class="nav-item nav-link" href="{% url 'register'%}">Register</a>  
                  {% endif %}

        				</div>
    	  		   </div>
    		</div>
  		</nav>
	</header>
	<!----- -->
	    	  		    
<main role="main" class="container">
 	<div class="row">
    	<div class="col-md-8">
    	   {% if messages %}
             {% for message in messages %}
                <div class = "alert alert-{{ message.tags }}" >
                    {{ message }}
                </div>
              {% endfor %}
            {% endif %}

          {% block content %}{% endblock %}

    	</div>
    	<div class="col-md-4">
    	  <div class="content-section">
        	<h3>Our Sidebar</h3>
        	<p class='text-muted'>\Information here you'd like.
          		<ul class="list-group">
            	<li class="list-group-item list-group-item-light"> <a href="{% url 'blog-home' %}">Latest Posts</a></li>
            	<li class="list-group-item list-group-item-light"><a href="https://www.instagram.com/azor1d/" target="_blank">Social media </a></li>
            	<li class="list-group-item list-group-item-light"><a href="{% url 'blog-about' %}">About us</a></li>
          		</ul>
        	</p>
    	  </div>
    	</div>
  	</div>
</main>


	<!----> 







   <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/comments.html
{% extends 'post_detail.html' %}
{% load static %}  
{% include 'crispy_forms/field.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ post.title }}{% endblock %}
{% block content %}
{% include 'post_detail.html' %}

{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
	{% for post in posts %}
		<article class="media content-section">
          	<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
		  <div class="media-body">
    		<div class="article-metadata">
    		  <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
		      <small class="text-muted">{{ post.date_posted|date:"d F, Y" }}</small>
    		</div>
    		<h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
    		<p class="article-content">{{ post.content }}</p>
		  </div>
		</article>
	{% endfor%}
	<!---PAGES----->
	{% if is_paginated %}
		{% if page_obj.has_previous %}
			<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number}}">Previous</a>
		{% endif %}

        {% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-4" href="?page={{ num}}">{{num }}</a>
				{% elif num > page_obj.number|add:'-3' and  num < page_obj.number|add:'3' %}
				<a class="btn btn-outline-info mb-4" href="?page={{ num}}">{{num }}</a>
			{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number  }}">Next</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		
		{% endif %}
	{% endif %}

{% endblock content%}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
	<!---->
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Delete Post</legend>
				<h2>Are you sure you want to delete the post"{{object.title}}"</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Yes, delete</button>
               <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
			</div>
		</form>
	</div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted|date:"d F, Y" }}</small>
            {% if object.author == user %}
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content }}</p>
    </div>
</article>

<div>
    <!-- LIKES -->
    {% if user.is_authenticated %}
    <form action="{% url 'post_like' object.id %}" method="POST">
        {% csrf_token %}
        {% if post_is_liked %}
        <button type="submit" name="post_id" value="{{ object.id }}" class="btn btn-info">Unlike</button>
        {% else %}
        <button type="submit" name="post_id" value="{{ object.id }}" class="btn btn-info">Like</button>
        {% endif %}
    </form>
    {% else %}
    <a class="btn btn-outline-info" href="{% url 'login' %}?next={{ request.path }}">Log in to like this article!</a><br>
    {% endif %}
    <strong class="text-secondary">{{ number_of_likes }} Like{{ number_of_likes|pluralize }}</strong>
</div>

<!-- List of comments -->
{% if comments %}
<div class="content-section mt-5">
    <div class="col-lg-6">
        Comment{{ comments.count|pluralize }}
        <span class="badge badge-dark ml-2">{{ comments.count }}</span>
    </div>
    {% for comment in comments %}
    <div class="col-lg-6">
        <div class="card p-2">
            <div class="row">
                <div class="col-12">
                    <p class="m-1 mt-3">{{ comment.content }}</p>
                    <p class="text-right text-muted"><small>{{ comment.date_commented }}</small></p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

<!-- Form to leave a comment -->
<div class="content-section mt-5">
    <h3>Leave a comment</h3>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.name.label_tag }}
            <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name"
                name="name" value="{{ form.name.value|default:'' }}">
        </div>
        <div class="form-group">
            {{ form.content.label_tag }}
            <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
                name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
        </div>
        <button class="btn btn-primary" type="submit">Reply</button>
    </form>
</div>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% include 'crispy_forms/field.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<!---->
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Blog post</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Post</button>
			</div>
		</form>
	</div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
	<h1 class = "mb-3">Posts by {{ view.kwargs.username}}
		({{ page_obj.paginator.count }})
	</h1>
	{% for post in posts %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ post.author.profile.image.url}}">
		  <div class="media-body">
    		<div class="article-metadata">
    		  <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
		      <small class="text-muted">{{ post.date_posted|date:"d F, Y" }}</small>
    		</div>
    		<h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
    		<p class="article-content">{{ post.content }}</p>
		  </div>
		</article>
	{% endfor%}
	<!---PAGES----->
	{% if is_paginated %}
		{% if page_obj.has_previous %}
			<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number}}">Previous</a>
		{% endif %}

        {% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-4" href="?page={{ num}}">{{num }}</a>
				{% elif num > page_obj.number|add:'-3' and  num < page_obj.number|add:'3' %}
				<a class="btn btn-outline-info mb-4" href="?page={{ num}}">{{num }}</a>
			{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number  }}">Next</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		
		{% endif %}
	{% endif %}

{% endblock content%}